### ISSUE TITLE
Collabora v6 destroys file with Excel Macros

### ISSUE THREAD

**Issue by Ich5003** [CollaboraOnline/online#1958]
**Describe the bug**
I have a file with Excel Macros, which works fine.
After editing this file with Collabora online (not using the Makros, just changing the values of a cell) the file becomes unreadable for Excel.
This bug appears in Collabora v6.x but everything works fine in v4.x

**To Reproduce**
1. Open the file with Excel Makros to see it works in Excel (you don't need to that that if you have security concerns, reproducing this also works without this step)
2. Open the file on Collabora online (e.g. CODE in Nextcloud, v.6,x)
3. Edit the value of any cell
4. Save the file
5. Try to open the file again in Excel => Excel fails to read the file

**Expected behavior**
Collabora should modify macros it does not understand. It should only save the changes made by the user, so the macros still work normally in Excel.

**Actual behavior**
Collabora saves a corrupted file.

**Additional context**
Everything worked fine in v4.x but fails in v6.x

**Example file to reproduce the error**

[2021_12_16_TO.xls](https://github.com/CollaboraOnline/online/files/6285937/2021_12_16_TO.xls)

**Comment by thebearon** [comment]
No problem here, I can open the file in Excel after open+save in Collabora Online, both with English and German locale. Which version are you using? If it's not the latest 6.4.7 version, can you upgrade and try again?

**Comment by Ich5003** [comment]
Hi @thebearon 
I recorded a video where I reproduce the bug: https://www.youtube.com/watch?v=WdVviMhmiiE

**Comment by MitchellHicks** [comment]
I would like to add i have collabroa/code docker image all of the versions that i have used[over the last year] do this same behavior.. buttons disappear and all macro code is gone... i can't upload my file since it is proprietary company information.. to if needed i can create a striped version with just button and code...
[this last version 6.4.8 (git hash: 4aa2794),Served by: 6573a97c does not auto-save on open/close so at least i can open view then close with out corrupting the file]

**Comment by Ich5003** [comment]
> I would like to add i have collabroa/code docker image all of the versions that i have used[over the last year] do this same behavior.. buttons disappear and all macro code is gone... i can't upload my file since it is proprietary company information.. to if needed i can create a striped version with just button and code...
> [this last version 6.4.8 (git hash: [4aa2794](https://github.com/CollaboraOnline/online/commit/4aa2794c621d8ac9f3482d74dc822cfb555239ed)),Served by: 6573a97c does not auto-save on open/close so at least i can open view then close with out corrupting the file]

It works for me with the docker image collabora/code:4.2.6.2, but version 4 is not maintained anymore. But you may try to use this version until they hopefully fix V6 soon.

**Comment by MitchellHicks** [comment]
@Ich5003 It's never worked for me EVER...  Ok so i made a very simple sample file of just a button that gets removed on save..

[CommandButton.xlsx](https://github.com/CollaboraOnline/online/files/6394077/CommandButton.xlsx)
just load this the button is there.. save and re open the button is gone...

This really can never happen with out a warning of some kind that writing/saving is going to in cure some for of data loss.

**Comment by MitchellHicks** [comment]
> > I would like to add i have collabroa/code docker image all of the versions that i have used[over the last year] do this same behavior.. buttons disappear and all macro code is gone... i can't upload my file since it is proprietary company information.. to if needed i can create a striped version with just button and code...
> > [this last version 6.4.8 (git hash: [4aa2794](https://github.com/CollaboraOnline/online/commit/4aa2794c621d8ac9f3482d74dc822cfb555239ed)),Served by: 6573a97c does not auto-save on open/close so at least i can open view then close with out corrupting the file]
> 
> It works for me with the docker image collabora/code:4.2.6.2, but version 4 is not maintained anymore. But you may try to use this version until they hopefully fix V6 soon.

I just tried it with 4.2.6.2 and the button is goes as well...

**Comment by MitchellHicks** [comment]
I'm confused... is no one else having this issue? or is there something wrong with my install that is causing this?
This is BLOCKING my company from being able to use the online editing at all... I don't need the button/macros to work.. i just need them to NOT GET REMOVED from the file...

**Comment by crespoeloy** [comment]
> I'm confused... is no one else having this issue? or is there something wrong with my install that is causing this?
> This is BLOCKING my company from being able to use the online editing at all... I don't need the button/macros to work.. i just need them to NOT GET REMOVED from the file...

Hi Mitchell - this is Eloy Crespo from Collabora. I see that this is a blocking issue for your company. Are you evaluating the possibility of getting support from us to be able to fix the issue?

**Comment by MitchellHicks** [comment]
I looked at the Collabora website and it seems that the cost would be
12,000(EU) for the minimum support package...
Making that a non starter... we have deployed nextcloud but are a small
install (less than 20 users).

I currently just have everyone set as READ only except me for testing with
each release.

if there is another option please let me know...

some improvements like not SAVING ON CLOSE anymore so at least you can open
and close without losing data...
but really there should at minimum be a WARNING like libreoffice does on
save that DATA is going to be LOST.

Thank's for your Time

Mitch

**Comment by crespoeloy** [comment]
Hello Mitchell,

We have other support options for your scenario. Please, feel free to send an email to hello@collaboraoffice.com and we will take it from there. 

BR,

Eloy

**Comment by Ich5003** [comment]
Hello,

@MitchellHicks is not the only one with this proble, this is a general one.
And in my opinion, even a free open source software should NEVER break something existing without any kind of warning.
This should not be a support case, but instead should be fixed in general!

**Comment by MitchellHicks** [comment]
Now Removed until patched. You can thank a creative user. I set everyone to read only to keep this from being an issue... well they opened the file and clicked SAVE AS.. causing all the buttons and code to be striped from the file [5 times]. so i had to migrate the data to a clean template file...

@crespoeloy This really is unacceptable you causing data loss and are making two excellent projects look bad with your direct association LibreOffice and Nextcloud.

@Ich5003 well they never even replayed to my request for a quote[not that they are required].

my guess is most people figure this out in testing and just don't deploy the suite at all(smarter then my self).


Mitch

**Comment by kendy** [comment]
@MitchellHicks: Really sorry to hear about your problem :-(  We have tried to reproduce it, and actually we can see it even with the plain LibreOffice, without the Collabora Online involved:

* Open the file with the desktop LibreOffice
* Hit Save and confirm you want to save in the OOXML format
* Close LibreOffice
* Open the file again and see the button gone.

I hope you understand Collabora Online cannot be responsible for bugs in LibreOffice. To get it sorted out, I'd encourage you to file it in the LibreOffice bugzilla instead:

https://bugs.documentfoundation.org/

All the best!

**Comment by vmiklos** [comment]
That being said, I improved the handling of command buttons just recently, available in the "2021 snapshot" version:

https://cgit.freedesktop.org/libreoffice/core/commit/?h=distro/collabora/co-2021&id=dc6c9a37f367fd28a45e70e6de98cb0b24e50040

I imagine we'll soon start publishing snapshot binaries of that.

**Comment by MitchellHicks** [comment]
> 
> 
> @MitchellHicks: Really sorry to hear about your problem :-( We have tried to reproduce it, and actually we can see it even with the plain LibreOffice, without the Collabora Online involved:
> 
>     * Open the file with the desktop LibreOffice
> 
>     * Hit Save and confirm you want to save in the OOXML format
> 
>     * Close LibreOffice
> 
>     * Open the file again and see the button gone.
> 
> 
> I hope you understand Collabora Online cannot be responsible for bugs in LibreOffice. To get it sorted out, I'd encourage you to file it in the LibreOffice bugzilla instead:
> 
> https://bugs.documentfoundation.org/
> 
> All the best!

and i am saving back in .xlsm format but the issue is the same... and you missed on the steps that the save dialog WARNS you that you might not get everything in the file.  

************** Please add this to the save dialog of Collabora *****************
'This document may contain formatting or content that cannot be saved in the currently seelct file format "Excel 2007-365 (macro-enabled)".'
*********************************************************************************

Yes you have missed the point.. you save with data loss with out a warning.

LibreOffice provides a warning in the save dialog that it is unable to save all the data[screen shot included]

![LibreOffice save dialog](https://user-images.githubusercontent.com/63065222/125509590-10f89c9b-5543-4cf5-bff8-77e71bd01d7c.png)

Again i don't expect you to add features that are not in LibreOffice..  or expect 100% feature matching[i know you are working that]
but i think everyone that has commented on this BUG has the same issue it saves with out any warning that you are losing data/information

@vmiklos That is very exciting to hear and I look forward to the amazing work you are doing.

**Comment by kendy** [comment]
@MitchellHicks: The problem is that it's impossible to know if the user is saving a document that could potentially lead to a data loss or not. Showing the dialog just always as LibreOffice does just defeats the purpose - there are millions of documents that save just fine, without any data loss.

We are currently working on a tool that will help us to identify areas that might lead to data loss, and implement those features similarly to what @vmiklos has done here. I do hope that will ultimately resolve issues like this.

Either way, thank you again for the report. In case you hit another problem like this, please do file it: In the LibreOffice bugzilla if you reproduce there; or here if it is Collabora Office-only problem. Thank you in advance!
