### ISSUE TITLE
CODE 6.4.7/6.4.8: Pasting PRIMARY with middle mouse button in Calc overwrites wrong cell.

### ISSUE THREAD

**Issue by gohrner** [CollaboraOnline/online#2055]
**Describe the bug**
Normally, in basically all spreadsheet applications you can paste the PRIMARY buffer contents with the middle mouse button into the cell pointed at by the mouse pointer.

CODE versions:

> LOOLWSD
6.4.7 (git hash: 4f68c25)
Angeboten von: 5db4dff8
LOKit
Collabora Office 6.4-33 (git hash: bec78a8)
"Ubuntu 18.04.5 LTS"

> LOOLWSD
6.4.8 (git hash: 4aa2794)
Angeboten von: 933fb759
LOKit
Collabora Office 6.4-36 (git hash: 3d919ce)
"Ubuntu 18.04.5 LTS"

**To Reproduce**
1. Copy some text to PRIMARY, e.g. by selecting it in a text editor like Kate or gedit.
2. Select a cell in Calc.
3. Move the mouse cursor to a different cell and press the middle mouse button.

**Expected behavior**
The PRIMARY contents will be pasted to the cell below the mouse pointer, as in every spreadsheet application I know (including Desktop version of LO Calc).

**Actual behavior**
The PRIMARY contents are pasted into the selected cell, even if it's not near the mouse pointer, overwriting its contents.

Also, copying text into PRIMARY by selecting it does not seem to work properly. Pressing F2 at a cell, selecting some text and then trying to paste it somewhere else using the middle mouse button mostly pastes old contents or empty text. It works fine in the LO Calc desktop version, and basically all other applications.

**Desktop (please complete the following information)**
 - OS: Ubuntu 20.04 x64 (KDE neon with KDE 5 Plasma Desktop)
 - Browser: Chromium
 - Version: Version 89.0.4389.90 (Offizieller Build) Built on Ubuntu , running on neon 20.04 (64-Bit)

**Comment by rpear** [comment]
@gohrner I think this is sort of fixed in 6.4.10.   Sort of? ....well nothing happens with the middle mouse button at all now, and if you right-click and paste instead, you are alerted with a pop-up informing you to use Ctrl+V instead due to browsers having limited access to the clipboard.  So perhaps the middle mouse button should pop-i the same alert?

**Comment by Ezinnem** [comment]
Closing this issue due to no response from the Author.

**Comment by gohrner** [comment]
This bug is still open as of 6.4.14:

```
LOOLWSD
6.4.14 (git hash: d28ff6e)
Angeboten von: f6ba5de4

LOKit
built on LibreOffice Technology
Collabora Office 6.4-50 (git hash: d53ee72)
"Ubuntu 18.04.6 LTS"
```

**Comment by gohrner** [comment]
@Ezinnem : How can I reopen this issue, it's not fixed in 6.4.14 at least.

**Comment by thebearon** [comment]
I can still reproduce this bug based on the actual description. It instructs to select a piece of text in an external program (no need to copy), and paste the selected text using the middle button. The text is pasted in the selected cell, not in the cell above which the mouse cursor currently is (compare behavior with LO desktop Calc).

**Comment by smehrbrodt** [comment]
Fixed with https://gerrit.collaboraoffice.com/plugins/gitiles/online/+/99da97fc1522733713cef222064a5f3a81bc7fc7%5E%21/
